# Use an official lightweight nginx image as a parent image
FROM nginx:stable-alpine

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Remove default nginx static files
RUN rm -rf ./*

# Copy the HTML file from your host to the container's working directory.
# Assuming that your project folder has only the index.html, or you could
# specify additional files or directories if necessary.
COPY index.html index.html

# Expose port 80 on the container to allow traffic to your app
EXPOSE 80

# Run nginx in the foreground to keep the container running.
CMD ["nginx", "-g", "daemon off;"]
